### 연습문제 1.1.2

$\alpha$와 $\beta$의 값이 같다.

$$ \alpha = \beta $$

$\gamma$와 $\delta$의 값이 같다.

$$ \gamma = \delta $$

$\epsilon$과 $\zeta$의 값이 같다.

$$ \epsilon = \zeta $$ 

$\eta$와 $\theta$의 값이 같다.

$$ \eta = \theta $$ 

$\kappa$와 $\lambda$의 값이 같다.

$$ \kappa = \lambda $$ 

$\mu$와 $\nu$의 값이 같다.

$$ \mu = \nu $$ 

$\xi$와 $\pi$의 값이 같다.

$$ \xi = \pi $$ 

$\rho$와 $\sigma$의 값이 같다.

$$ \rho = \sigma $$ 

$\tau$와 $\phi$의 값이 같다.

$$ \tau = \phi $$ 

$\chi$와 $\psi$의 값이 같다.

$$ \chi = \psi $$ 

$\psi$와 $\omega$의 값이 같다.

$$ \psi = \omega $$ 

In [16]:
### 2-1) 데이터와 행렬

In [17]:
from sklearn.datasets import load_iris

In [18]:
iris = load_iris()
iris.data[0, :] # 0안의 모든 데이터

array([5.1, 3.5, 1.4, 0.2])

### 연습 문제 2.1.1
- NumPy를 사용해서 붓꽃 데이터  x2 에 대한 벡터 변수 x2를 만든다.

In [27]:
import numpy as np

In [28]:
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])
x2

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

### 연습 문제 2.1.2
- 넘파이를 사용해서 붓꽃 데이터  X 에 대한 행렬 변수 X를 만든다.

In [30]:
x = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

### 연습 문제 2.1.3¶
- NumPy를 사용해서 붓꽃 데이터  X 의 전치행렬  XT 을 구한다.
- NumPy를 사용해서 위 전치행렬을 다시 전치한 행렬  (XT)T 을 구한다. 이 행렬과 원래 행렬  X 을 비교한다.

In [33]:
x.T # 전치 연산

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [32]:
x.T.T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [39]:
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [37]:
np.diag((1, 2, 3)) # 대각 성분에 들어갈 숫자 지정

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [41]:
np.identity((3)) # 크기만 적어준다

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 연습 문제 2.1.4
- 영벡터, 일벡터, 정방행렬, 대각행렬, 항등행렬, 대칭행렬의 예를 하나씩 만들어본다.
- 위의 벡터와 행렬을 NumPy로 나타내 본다.

In [51]:
import numpy as np
np.zeros((3,1)) # 영벡터

array([[0.],
       [0.],
       [0.]])

In [52]:
np.ones((4,1))# 일벡터

array([[1.],
       [1.],
       [1.],
       [1.]])

In [53]:
np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]) # 정방행렬

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [54]:
np.diag((2, 4, 5, 6)) # 대각행렬

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [58]:
np.identity(5) # 항등행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.eye(5) # 항등행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.array([[1, 2, 3, 4], [2, 3, 4, 1], [3, 4, 1, 2], [4, 1, 2, 3]]) # 대칭행렬

array([[1, 2, 3, 4],
       [2, 3, 4, 1],
       [3, 4, 1, 2],
       [4, 1, 2, 3]])

In [67]:
# 행렬과 벡터의 내적
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])
x.T @ y
np.dot(x.T, y)

array([[32]])

In [68]:
# 2차원 행렬에서 값만 빼내고 싶을 때
(x.T @ y)[0][0]

32

In [65]:
x = np.array([1, 2, 3]) # 1차원 벡터의 내적
y = np.array([4, 5, 6])
x @ y
np.dot(x, y)

32

# 연습 문제 2.2.1¶
- A, B, C 세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.
- (1) 주식의 가격과 수량을 각각  p  벡터,  n  벡터로 표시하고 넘파이로 코딩한다.
- (2) 주식을 매수할 때 필요한 금액을 곱셈으로 표시하고 넘파이 연산으로 그 값을 계산한다.

In [77]:
stock = np.array([[100], [80], [50]])
w = np.array([[3], [4], [5]])
(w.T @ stock)[0][0] # np.dot(w.T, stock)

870

In [78]:
# 가중평균
x = np.arange(10)
N = len(x)

np.ones(N) @ x / N

4.5

In [79]:
x.mean() #편하다

4.5

### 연습 문제 2.2.3
- 다음 코드를 실행하면 MNIST 숫자 이미지 전체 데이터를 모두 벡터로 변환하여 하나의 넘파이 행렬 X를 만든다.
- 이 행렬을 이용하여 다음 문제를 풀어라.
- from sklearn.datasets import load_digits 
- X = load_digits().data # 이미지 데이터가 나온다
    - (1) 내적을 이용하여 첫 번째 이미지와 10번째 이미지의 유사도를 구하라.
    - (2) 내적을 이용하여 모든 이미지의 조합에 대해 유사도를 구하라. 어떻게 구현하는 것이 효율적일까? (힌트 : 이 문제는 뒤에서 배울 행렬과 행렬의 곱셈을 이용한다.)

In [95]:
import numpy as np
from sklearn.datasets import load_digits

In [96]:
data = load_digits()
x = data.data
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [101]:
x[0, : ].T @ x[1, : ] # 유사도

1866.0

In [102]:
np.dot(x[3, : ].T, x[5, : ])

3137.0

### 연습 문제 2.2.4
- (3)  A ,  B 가 다음과 같을 때,  AB ,  BA 를 (계산이 가능하다면) 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다.  AB ,  BA  모두 계산 가능한가?
    - A=[123]
    - B=⎡⎣⎢456789⎤⎦⎥
- (4) A, B가 다음과 같을 때, AB, BA를 (계산이 가능하다면) 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. AB, BA 모두 계산 가능한가? BA의 결과가 AB와 같은가?
    - A=[1324]
    - B=[5768]
- (5) A가 다음과 같을 때, AAT와 ATA를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. AAT와 ATA의 크기는 어떠한가? 항상 정방행렬이 되는가?
    - A=⎡⎣⎢135246⎤⎦⎥
- (6) x가 다음과 같을 때, xTx와 xxT를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. xTx와 xxT의 크기는 어떠한가? 어떤 것이 스칼라이고 어떤 것이 정방행렬인가?
    - x=⎡⎣⎢123⎤⎦⎥

In [112]:
b = np.array([[4, 7], [5, 8], [6, 9]])
a = np.array([[1, 2, 3]])
a @ b # b @ a는 에러!

array([[32, 50]])

In [115]:
a = np.array([[5, 6], [7, 8]])
b = np.array([[1, 2], [3, 4]])
a @ b

array([[23, 34],
       [31, 46]])

In [116]:
b @ a

array([[19, 22],
       [43, 50]])

In [118]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a @ a.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [119]:
a.T @ a

array([[35, 44],
       [44, 56]])

In [123]:
x = np.array([[1], [2], [3]])
x.T @ x

array([[14]])

In [122]:
x @ x.T

array([[14]])