In [2]:
import numpy as np

In [3]:
A = (np.arange(9) - 4).reshape((3, 3))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [4]:
np.linalg.norm(A) # A 행렬의 크기(놈) 값을 구한다.

7.745966692414834

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
A_inv = np.linalg.inv(A) # a 행렬의 역행렬
A_inv

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [7]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [8]:
# Ax = b 선형 연립방정식(연립 1차 방정식)
# x = (A ** -1) * b
x = A_inv @ b
x

array([[ 4.],
       [-4.],
       [ 2.]])

In [9]:
# 리스트 스퀘어 사용해 연립방정식을 풀어주는 방법
x, resid, rank, s = np.linalg.lstsq(A, b)
x

/Users/Im/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


array([[-0.05555556],
       [ 0.11111111],
       [ 0.27777778]])

In [10]:
# 연습문제 2.4.5 보스턴 집값 문제
from sklearn.datasets import load_boston
boston = load_boston() # 클래스, 객체 선언
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]] # 'CRIM', 'NOX', 'RM', 'AGE' 일부 데이터만 뽑는다, 인덱스가 0, 4, 5, 6
b = y[:4] # 타운도 0~3번까지만

In [11]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [12]:
b

array([24. , 21.6, 34.7, 33.4])

In [13]:
w = np.linalg.inv(A) @ b
w

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [14]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [15]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [16]:
# 의사 역행렬 직접 계산
Apinv = np.linalg.inv(A.T @ A) @ A.T # np.linalg.inv()는 역행렬 구하는 함수
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [17]:
# 구한 의사 역행렬 값을 대입해 최소자승문제 해결
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [18]:
# 확인
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [19]:
# 리스트스퀘어 이용해 최소자승문제 해결
x, resid, rank, s = np.linalg.lstsq(A, b)
x

/Users/Im/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [20]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [21]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [22]:
import numpy as np
a = np.array([[4], [5], [2], [2]])
b = np.array([[4], [0], [2], [0]])
c = np.array([[2], [2], [0], [1]])

In [23]:
# 유클리드 거리
result = np.linalg.norm(a - b)
result1 = np.linalg.norm(b - c)
result2 = np.linalg.norm(c - a)
result, result1, result2

(5.385164807134504, 3.605551275463989, 4.242640687119285)

In [24]:
# 코사인 거리 1 - 코사인 유사도
print("a와 b의 코사인 거리: ", 1 - ((a.T @ b)[0][0] / (np.linalg.norm(a) * np.linalg.norm(b))))
print("b와 c의 코사인 거리: ", 1 - ((b.T @ c)[0][0] / (np.linalg.norm(b) * np.linalg.norm(c))))
print("c와 a의 코사인 거리: ", 1 - ((c.T @ a)[0][0] / (np.linalg.norm(c) * np.linalg.norm(a))))

a와 b의 코사인 거리:  0.36112343500006017
b와 c의 코사인 거리:  0.40371520600005606
c와 a의 코사인 거리:  0.04761904761904767
